name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.10"

      - name: Build package
        run: uv build
        shell: bash

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
