name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: "pip"

      - name: Install uv
        run: pipx install uv
        shell: bash

      - name: Install dependencies
        run: uv install
        shell: bash

      - name: Build package
        run: uv build
        shell: bash

      - name: Publish package
        run: |
          uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
        shell: bash
